# Generated by Django 5.2.1 on 2026-01-03 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_resource', models.CharField(blank=True, max_length=100)),
                ('resource_unit', models.CharField(choices=[('cft', 'Cft'), ('sft', 'Sft'), ('nos', 'Nos'), ('pcs', 'Pcs'), ('rm', 'Rm'), ('rft', 'Rft')], help_text='Unit of measurement for the work', max_length=20)),
                ('resource_group', models.CharField(choices=[('civil work', 'Civil Work'), ('sanitary work', 'Sanitary Work'), ('electrical work', 'Electrical Work'), ('tiles work', 'Tiles Work')], help_text='Unit of measurement for the work', max_length=20)),
                ('team', models.CharField(choices=[('rm', 'RM')], help_text='Team responsible for this resource', max_length=50)),
                ('allow_team_edit', models.BooleanField(default=False, help_text='If True, allows the team member who created this record to edit/delete it')),
                ('edit_request_pending', models.BooleanField(default=False, help_text='If True, indicates the team member has requested edit/delete access')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('created_by', models.ForeignKey(help_text='User who created this resource record', on_delete=django.db.models.deletion.CASCADE, related_name='created_resource', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this resource record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_resource', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resource Detail',
                'verbose_name_plural': 'Resource Details',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('rm', 'RM')], default='rm', help_text="Defines the user's role in resource operations", max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resource_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resource Role Profile',
                'verbose_name_plural': 'Resource Role Profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
